version: 2.1

jobs:
  self-update:
    docker:
      - image: cimg/python:3.9
    steps:
      - run: |
          which poetry
          poetry --version
      - run: |
          # force downgrade
          poetry self update 1.2.1
      - run: |
          poetry --version

workflows:
  main:
    jobs:
      - self-update
